.TH "TracknTrace/TracknTrace/analysis.py" 3 "Smart Meter Interpreter Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TracknTrace/TracknTrace/analysis.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTracknTrace\fP"
.br
.ti -1c
.RI "namespace \fBTracknTrace\&.analysis\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDegreeDays\fP (data, Log)"
.br
.RI "Calculate Degreedays based on outside temperature and livingroom temperature\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Meter Interpreter Documentation from the source code\&.
