.TH "TracknTrace/TracknTrace/fimufit/mufit Directory Reference" 3 "Smart Meter Interpreter Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TracknTrace/TracknTrace/fimufit/mufit Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBbulkglassfit\&.py\fP"
.br
.ti -1c
.RI "file \fBmain\&.py\fP"
.br
.in -1c
