.TH "TracknTrace/TracknTrace Directory Reference" 3 "Smart Meter Interpreter Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TracknTrace/TracknTrace Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcategorizer\fP"
.br
.ti -1c
.RI "directory \fBfimufit\fP"
.br
.ti -1c
.RI "directory \fBpreprocessor\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBanalysis\&.py\fP"
.br
.ti -1c
.RI "file \fBwrapper\&.py\fP"
.br
.in -1c
