.TH "TracknTrace/TracknTrace/fimufit/mufit/main.py" 3 "Smart Meter Interpreter Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TracknTrace/TracknTrace/fimufit/mufit/main.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMultiFitter\fP"
.br
.RI "The \fBMultiFitter\fP base class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmufit\fP"
.br
.ti -1c
.RI "namespace \fBmufit\&.main\fP"
.br
.RI "Defines the \fBMultiFitter\fP classes\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.RI "Example main to run if file is not being imported\&. "
.ti -1c
.RI "\fBProfileGenerator\fP (length, \fBProfile\fP)"
.br
.RI "Profile generator function, returns a dataframe with the profile\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBProfile\fP"
.br
.RI "Example profile dictionary as input for the generator\&. "
.ti -1c
.RI "\fBSimThis\fP = \fBProfileGenerator\fP(100,\fBProfile\fP)"
.br
.RI "An Example generated profile\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Meter Interpreter Documentation from the source code\&.
