.TH "mufit" 3 "Smart Meter Interpreter Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mufit
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbulkglassfit\fP"
.br
.ti -1c
.RI "namespace \fBmain\fP"
.br
.RI "Defines the \fBMultiFitter\fP classes\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Meter Interpreter Documentation from the source code\&.
