.TH "mufit.main" 3 "Smart Meter Interpreter Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mufit.main \- Defines the \fBMultiFitter\fP classes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMultiFitter\fP"
.br
.RI "The \fBMultiFitter\fP base class\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.RI "Example main to run if file is not being imported\&. "
.ti -1c
.RI "\fBProfileGenerator\fP (length, \fBProfile\fP)"
.br
.RI "Profile generator function, returns a dataframe with the profile\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBProfile\fP"
.br
.RI "Example profile dictionary as input for the generator\&. "
.ti -1c
.RI "\fBSimThis\fP = \fBProfileGenerator\fP(100,\fBProfile\fP)"
.br
.RI "An Example generated profile\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the \fBMultiFitter\fP classes\&. 
.SH "Function Documentation"
.PP 
.SS "main ()"

.PP
Example main to run if file is not being imported\&. 
.PP
Definition at line \fB687\fP of file \fBmain\&.py\fP\&.
.PP
References \fBmain()\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "ProfileGenerator ( length,  Profile)"

.PP
Profile generator function, returns a dataframe with the profile\&. 
.PP
\fBParameters\fP
.RS 4
\fIlength\fP the length of the dataset to be generated 
.br
\fIProfile\fP A dictionary with name:array pairs where the array has format [value,upto,value,upto,etc\&.\&.\&.\&.] 
.br
\fIverbose\fP verbose boolean generates more output for debugging
.RE
.PP
\fBReturns\fP
.RS 4
A Pandas dataFrame of length with the specified profile 
.RE
.PP

.PP
Definition at line \fB52\fP of file \fBmain\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "dict Profile"
\fBInitial value:\fP
.nf
1 =  {"Tenv":[10,20,18,40,25,60,18,80,8,100],
2            "Pe":[700,10,200,20,0,60,700,100], # 700W power up to point 10, then 200W up to point 20, then 0 W up to 60 and finally 700W up to point 100
3            "Tobj":[24,100],
4            "Psol":[0,10,100,20,200,30,300,40,250,50,225,60,200,70,175,80,125,90,0,100]}
.PP
.fi

.PP
Example profile dictionary as input for the generator\&. 
.PP
Definition at line \fB47\fP of file \fBmain\&.py\fP\&.
.SS "SimThis = \fBProfileGenerator\fP(100,\fBProfile\fP)"

.PP
An Example generated profile\&. 
.PP
Definition at line \fB71\fP of file \fBmain\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Meter Interpreter Documentation from the source code\&.
