.TH "mufit.bulkglassfit" 3 "Smart Meter Interpreter Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mufit.bulkglassfit
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "main ()"

.PP
Definition at line \fB3\fP of file \fBbulkglassfit\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Meter Interpreter Documentation from the source code\&.
