.TH "setup" 3 "Smart Meter Interpreter Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setup
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBauthor\fP"
.br
.ti -1c
.RI "\fBauthor_email\fP"
.br
.ti -1c
.RI "\fBclassifiers\fP"
.br
.ti -1c
.RI "\fBdescription\fP"
.br
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBentry_points\fP"
.br
.ti -1c
.RI "\fBinclude_package_data\fP"
.br
.ti -1c
.RI "\fBinstall_requires\fP"
.br
.ti -1c
.RI "\fBkeywords\fP"
.br
.ti -1c
.RI "\fBlicense\fP"
.br
.ti -1c
.RI "\fBlong_description\fP = fh\&.read()"
.br
.ti -1c
.RI "\fBlong_description_content_type\fP"
.br
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBpackage_data\fP"
.br
.ti -1c
.RI "\fBpackages\fP"
.br
.ti -1c
.RI "\fBurl\fP"
.br
.ti -1c
.RI "\fBversion\fP"
.br
.ti -1c
.RI "\fBzip_safe\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "author"

.PP
Definition at line \fB25\fP of file \fBsetup\&.py\fP\&.
.SS "author_email"

.PP
Definition at line \fB26\fP of file \fBsetup\&.py\fP\&.
.SS "classifiers"

.PP
Definition at line \fB13\fP of file \fBsetup\&.py\fP\&.
.SS "description"

.PP
Definition at line \fB9\fP of file \fBsetup\&.py\fP\&.
.SS "encoding"

.PP
Definition at line \fB4\fP of file \fBsetup\&.py\fP\&.
.SS "entry_points"

.PP
Definition at line \fB46\fP of file \fBsetup\&.py\fP\&.
.SS "include_package_data"

.PP
Definition at line \fB12\fP of file \fBsetup\&.py\fP\&.
.SS "install_requires"

.PP
Definition at line \fB32\fP of file \fBsetup\&.py\fP\&.
.SS "keywords"

.PP
Definition at line \fB23\fP of file \fBsetup\&.py\fP\&.
.SS "license"

.PP
Definition at line \fB27\fP of file \fBsetup\&.py\fP\&.
.SS "long_description = fh\&.read()"

.PP
Definition at line \fB5\fP of file \fBsetup\&.py\fP\&.
.SS "long_description_content_type"

.PP
Definition at line \fB11\fP of file \fBsetup\&.py\fP\&.
.SS "name"

.PP
Definition at line \fB7\fP of file \fBsetup\&.py\fP\&.
.SS "package_data"

.PP
Definition at line \fB31\fP of file \fBsetup\&.py\fP\&.
.SS "packages"

.PP
Definition at line \fB28\fP of file \fBsetup\&.py\fP\&.
.SS "url"

.PP
Definition at line \fB24\fP of file \fBsetup\&.py\fP\&.
.SS "version"

.PP
Definition at line \fB8\fP of file \fBsetup\&.py\fP\&.
.SS "zip_safe"

.PP
Definition at line \fB51\fP of file \fBsetup\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Meter Interpreter Documentation from the source code\&.
