.TH "test_mufit" 3 "Smart Meter Interpreter Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_mufit
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetupLinear\fP (a=33\&.298490, b=\-7\&.5483425)"
.br
.ti -1c
.RI "\fBtest_AnalyzeBulkEvolver\fP (\fBTI2\fP)"
.br
.ti -1c
.RI "\fBtest_analyzeErrors\fP (\fBTI\fP)"
.br
.ti -1c
.RI "\fBtest_Evolving\fP (\fBTI\fP)"
.br
.ti -1c
.RI "\fBtest_Loading\fP (\fBTI\fP)"
.br
.ti -1c
.RI "\fBtest_SearchMap\fP (\fBTI\fP)"
.br
.ti -1c
.RI "\fBTI\fP ()"
.br
.ti -1c
.RI "\fBTI2\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdf\fP = \fBsetupLinear\fP()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "setupLinear ( a = \fR33\&.298490\fP,  b = \fR\-7\&.5483425\fP)"

.PP
Definition at line \fB4\fP of file \fBtest_mufit\&.py\fP\&.
.SS "test_AnalyzeBulkEvolver ( TI2)"

.PP
Definition at line \fB82\fP of file \fBtest_mufit\&.py\fP\&.
.SS "test_analyzeErrors ( TI)"

.PP
Definition at line \fB70\fP of file \fBtest_mufit\&.py\fP\&.
.SS "test_Evolving ( TI)"

.PP
Definition at line \fB43\fP of file \fBtest_mufit\&.py\fP\&.
.SS "test_Loading ( TI)"

.PP
Definition at line \fB28\fP of file \fBtest_mufit\&.py\fP\&.
.SS "test_SearchMap ( TI)"

.PP
Definition at line \fB56\fP of file \fBtest_mufit\&.py\fP\&.
.SS "TI ()"

.PP
Definition at line \fB12\fP of file \fBtest_mufit\&.py\fP\&.
.SS "TI2 ()"

.PP
Definition at line \fB20\fP of file \fBtest_mufit\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "df = \fBsetupLinear\fP()"

.PP
Definition at line \fB24\fP of file \fBtest_mufit\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Meter Interpreter Documentation from the source code\&.
