.TH "TracknTrace/TracknTrace/fimufit/tests/test_mufit.py" 3 "Smart Meter Interpreter Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TracknTrace/TracknTrace/fimufit/tests/test_mufit.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtest_mufit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetupLinear\fP (a=33\&.298490, b=\-7\&.5483425)"
.br
.ti -1c
.RI "\fBtest_AnalyzeBulkEvolver\fP (\fBTI2\fP)"
.br
.ti -1c
.RI "\fBtest_analyzeErrors\fP (\fBTI\fP)"
.br
.ti -1c
.RI "\fBtest_Evolving\fP (\fBTI\fP)"
.br
.ti -1c
.RI "\fBtest_Loading\fP (\fBTI\fP)"
.br
.ti -1c
.RI "\fBtest_SearchMap\fP (\fBTI\fP)"
.br
.ti -1c
.RI "\fBTI\fP ()"
.br
.ti -1c
.RI "\fBTI2\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdf\fP = \fBsetupLinear\fP()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Meter Interpreter Documentation from the source code\&.
