.TH "TracknTrace.wrapper" 3 "Smart Meter Interpreter Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TracknTrace.wrapper
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.RI "Log = ""\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "main ()"

.PP
Log = ""\&. 
.PP
Definition at line \fB9\fP of file \fBwrapper\&.py\fP\&.
.PP
References \fBmain()\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Meter Interpreter Documentation from the source code\&.
