Smart Meter Interpreter Documentation: MultiFitter Class Reference
MultiFitter Class Reference
The MultiFitter base class.
Public Member Functions
__init__ (self, Instance, lambdaMap=None, lambdaDict=None, verbose=0)
The multifitter base class initializer.
AnalyzeErrors (self)
Error analysis and sorting function, puts best found parameters in constants.
ArrayToConstants (self, Array)
load an array of constants; expects same length and order as internal dictionary!
BulkError (self, params, err, Iterations=None)
Do optimization run for scipy solver.
BulkEvolver (self, err, constraints=None, N=10, repeats=25, Iterations=None)
Calculate (self)
Retrieves all current variables, constants and predictors, filles them into lambdafunctions and puts the results into predictors.
dictSlice (self, index)
return a dictionary slice from the loaded dataframe
dictToArray (self, Dict)
convert dictionary to array
Evolver (self, err, N=10)
Evolution inspired parameter search algorithm.
Fiddler (self, curr, previousR, currentR, constantIndex)
Parameter transformer/gradient descent algorithm.
loadConstants (self, constDict=None)
Load a dictionary of constants and update solvelist too.
loadData (self, df, initPredictors=True)
Load pandas dataframe for simulation/prediction/parameter fitting.
loadPredictors (self, constDict=None)
Load a dictionary of predictors.
loadVariables (self, varDict=None)
Load a dictionary of variables and add in dt.
parameters (self)
Retrieves all current variables, constants and predictors.
parameterSearchMap (self, constraints=None, err=None, ims=4, steps=None)
Do parameter search over a defined area, results in steps*(constants^ims) iterations.
plotError (self, All=False)
Plots the internal error array of shape [index, error, c0, c1, cn....
resampleData (self, timeStep)
Internal dataframe resampler; this is not a smart function!
resetIndex (self)
reset the index to 0 and reset predictors and variables from SDF[0] IF SDF is defined
scipyOptimize (self, constraints=None, err=None, steps=None, iterations=1000, solver=None, lsq=False)
Do parameter optimization with scipy.optimize.
setSolveList (self, Array=None, Dict=None)
Set the constants to solve, can take an array of indexes/names or dict with new values.
SimSolve (self, steps, repeats, err)
Subsequent simulating and evolution based algorithm to test results.
Simulate (self, steps, err=None, write=True)
Apply the model (Calculate) to the loaded data, does not strictly need a DF.
stepIndex (self)
Step through the index and reset it once datalength is exceeded.
storeJson (self, data=None)
writeSlice (self)
write the current predictors to SDF simulation dataframe
Public Attributes
columns = columns
dict constants = {}
The constants stay constant unless fitted.
constraints = constraints
int dataLength
The loaded dataFrame length.
DF = df
The loaded pandas dataFrame.
int dt = 1
list error = []
int index = 0
The error array contains [index, error, [constants]].
str Instance = "{}.json".format(Instance)
dict lambdaDict = lambdaDict
dict lambdaMap = lambdaMap
LoadedInstance = self.storeJson()
dict predictors = {}
The predictors calculated by applying lambdafunctions.
pSearchMap = pSearchMap
SDF = pd.concat([self.SDF,pd.Series(self.predictors).to_frame().T], ignore_index=True)
The loaded dataFrame length.
dict solveList = {}
The solvelist so that not all constants have to be fitted.
dict variables = {"dt": 1.0}
The variables change every step.
Verbose = verbose
The verbose boolean.
Detailed Description
The MultiFitter base class.
Defines the base class which enables parameter fitting, loading data, visualization, simulation
Definition at line 73 of file main.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, Instance, lambdaMap = None, lambdaDict = None, verbose = 0)
The multifitter base class initializer.
Parameters
lambdaMap lambdaMap dictionary with array of variables, constants have a prefix of $ when they have to be fitted, * if they are truly constant
lambdaDict lambdaDict dictionary with lambdafunctions
verbose verbose boolean generates more output for debugging
Returns
An instance of the Sensor class initialized with the specified name.
Definition at line 78 of file main.py.
Member Function Documentation
AnalyzeErrors()
AnalyzeErrors (self)
Error analysis and sorting function, puts best found parameters in constants.
Returns
An array with errors in the format of [index,error,yreal,ypred,c0,c1,cn....]
Definition at line 571 of file main.py.
References constants, dataLength, error, storeJson(), and Verbose.
Referenced by plotError().
ArrayToConstants()
ArrayToConstants (self, Array)
load an array of constants; expects same length and order as internal dictionary!
Parameters
Array An array formatted to the same format as self.Constants
Definition at line 249 of file main.py.
References constants, loadConstants(), solveList, and Verbose.
Referenced by BulkEvolver().
BulkError()
BulkError (self, params, err, Iterations = None)
Do optimization run for scipy solver.
Parameters
params parameter array, generated by scipy.
err error objective
Returns
The accumulated error for the last simulation run
Definition at line 333 of file main.py.
References constants, dataLength, resetIndex(), Simulate(), solveList, and Verbose.
Referenced by BulkEvolver(), and scipyOptimize().
BulkEvolver()
BulkEvolver (self, err, constraints = None, N = 10, repeats = 25, Iterations = None)
Definition at line 437 of file main.py.
References ArrayToConstants(), BulkError(), constants, dictToArray(), Fiddler(), Simulate(), solveList, storeJson(), and Verbose.
Calculate()
Calculate (self)
Retrieves all current variables, constants and predictors, filles them into lambdafunctions and puts the results into predictors.
Definition at line 179 of file main.py.
References lambdaDict, lambdaMap, parameters(), predictors, and Verbose.
Referenced by Simulate().
dictSlice()
dictSlice (self, index)
return a dictionary slice from the loaded dataframe
Parameters
index index from DF to return
Returns
A dictionary with parameters found at DF[index]
Definition at line 273 of file main.py.
References DF.
Referenced by Simulate().
dictToArray()
dictToArray (self, Dict)
convert dictionary to array
Parameters
Dict dictionary to convert
Returns
An array with the dictionaries values
Definition at line 264 of file main.py.
Referenced by BulkEvolver(), and Simulate().
Evolver()
Evolver (self, err, N = 10)
Evolution inspired parameter search algorithm.
Parameters
err name of predictor (and dataframe column) that will be used for error determination; prediction target.
N amount of iteration to optimize each parameter that is in the solveList
Returns
An array with errors in the format of [index,error,c0,c1,cn....]
Definition at line 482 of file main.py.
References constants, error, Fiddler(), index, predictors, Simulate(), solveList, variables, and Verbose.
Referenced by SimSolve().
Fiddler()
Fiddler (self, curr, previousR, currentR, constantIndex)
Parameter transformer/gradient descent algorithm.
Parameters
curr current parameter that will be transformed, change is proportional to this.
previousR previous error array, this is used to determine the best direction to change towards
currentR current error array, as mentioned, to implement some form of gradient descent
constantIndex index of the current constant that is modified, needed to know what parameter in error array to look at
Returns
A new constant to try
Definition at line 401 of file main.py.
References Verbose.
Referenced by BulkEvolver(), and Evolver().
loadConstants()
loadConstants (self, constDict = None)
Load a dictionary of constants and update solvelist too.
Parameters
constDict dictionary with new constants and values
Definition at line 211 of file main.py.
References constants, LoadedInstance, solveList, storeJson(), and Verbose.
Referenced by ArrayToConstants().
loadData()
loadData (self, df, initPredictors = True)
Load pandas dataframe for simulation/prediction/parameter fitting.
Parameters
df pandas dataframe to load, this will also define SDF and datalength
initPredictors Boolean which fills the predictor dictionary with initial values from the dataframe
Definition at line 536 of file main.py.
loadPredictors()
loadPredictors (self, constDict = None)
Load a dictionary of predictors.
Parameters
constDict a dictionary with new predictors
Definition at line 235 of file main.py.
References constants, predictors, and Verbose.
Referenced by resetIndex().
loadVariables()
loadVariables (self, varDict = None)
Load a dictionary of variables and add in dt.
Parameters
varDict dictionary with new variables and values
Definition at line 197 of file main.py.
References dt, variables, and Verbose.
Referenced by resetIndex(), and Simulate().
parameters()
parameters (self)
Retrieves all current variables, constants and predictors.
Returns
A dictionary with variables, constants and predictors
Definition at line 171 of file main.py.
References constants, predictors, and variables.
Referenced by Calculate().
parameterSearchMap()
parameterSearchMap (self, constraints = None, err = None, ims = 4, steps = None)
Do parameter search over a defined area, results in steps*(constants^ims) iterations.
Parameters
constraints dictionary of arrays with [min,max] values to constraint the parameter search to example: SMap = {"U":[0.01,45.0],"C":[100,200]}
err Name of variable to track as error, make sure this is in the predictors and in the loaded data
ims Intermediate steps to generate, if 0 and 1 are given, a parameter search for 0, 0.25, 0.5 and 1 will be executed
Returns
An array with errors in the format of [index,error,c0,c1,cn....]
Definition at line 357 of file main.py.
plotError()
plotError (self, All = False)
Plots the internal error array of shape [index, error, c0, c1, cn....
]
Parameters
All if set to true, all errors are shown. Otherwise only best parameters for each timestep. Plotly plot
Definition at line 597 of file main.py.
References AnalyzeErrors(), columns, error, and solveList.
resampleData()
resampleData (self, timeStep)
Internal dataframe resampler; this is not a smart function!
make sure data is time dependent.
Parameters
timeStep Resample step in seconds; only works when the loaded data uses a datetime index!
Definition at line 558 of file main.py.
References dataLength, DF, dt, and Verbose.
resetIndex()
resetIndex (self)
reset the index to 0 and reset predictors and variables from SDF[0] IF SDF is defined
Definition at line 289 of file main.py.
References index, loadPredictors(), loadVariables(), and SDF.
Referenced by BulkError(), and Simulate().
scipyOptimize()
scipyOptimize (self, constraints = None, err = None, steps = None, iterations = 1000, solver = None, lsq = False)
Do parameter optimization with scipy.optimize.
Parameters
constraints dictionary of arrays with [min,max] values to constraint the parameter search to example: SMap = {"U":[0.01,45.0],"C":[100,200]}. If not given, all in solveList will be optimized without constraints
err Name of variable to track as error, make sure this is in the predictors and in the loaded data
steps amount of dataset steps to calculate in the error function
iterations amount of allowed solver iterations, default set to 1000
solver solving algorithm to be used, default nelder-mead
lsq treat problem as least-squares problem
Returns
An array with the best parameters found
Definition at line 297 of file main.py.
References BulkError(), solveList, and Verbose.
setSolveList()
setSolveList (self, Array = None, Dict = None)
Set the constants to solve, can take an array of indexes/names or dict with new values.
Parameters
Array An array with indexes or string names which can be found in constants and should be solved
Dict A dictionary with key:value pairs where key=name and value = initial value
Definition at line 616 of file main.py.
References constants, and solveList.
SimSolve()
SimSolve (self, steps, repeats, err)
Subsequent simulating and evolution based algorithm to test results.
Parameters
steps amount of iteration to optimize each parameter that is in the solveList and steps to simulate
repeats amount of times to repeat this loop of simulate -> evolve
err name of predictor (and dataframe column) that will be used for error determination; prediction target.
Returns
An array with errors in the format of [index,error,c0,c1,cn....]
Definition at line 672 of file main.py.
References error, Evolver(), and Simulate().
Simulate()
Simulate (self, steps, err = None, write = True)
Apply the model (Calculate) to the loaded data, does not strictly need a DF.
Parameters
steps amount of steps to simulate
err name of predictor (and dataframe column) that will be used for error determination; prediction target.
write if set to false, no data is written to SDF. This is used internally to test errors without tainting SDF
Returns
An array with errors in the format of [index,error,c0,c1,cn....] if err is defined, otherwise True
Definition at line 638 of file main.py.
References Calculate(), constants, dictSlice(), dictToArray(), error, index, loadVariables(), predictors, resetIndex(), stepIndex(), and writeSlice().
Referenced by BulkError(), BulkEvolver(), Evolver(), and SimSolve().
stepIndex()
stepIndex (self)
Step through the index and reset it once datalength is exceeded.
Definition at line 529 of file main.py.
References index.
Referenced by Simulate().
storeJson()
storeJson (self, data = None)
Definition at line 156 of file main.py.
References index, and Instance.
Referenced by AnalyzeErrors(), BulkEvolver(), and loadConstants().
writeSlice()
writeSlice (self)
write the current predictors to SDF simulation dataframe
Definition at line 282 of file main.py.
References predictors.
Referenced by Simulate().
Member Data Documentation
columns
columns = columns
Definition at line 137 of file main.py.
Referenced by Eventor.GenericEvents(), and plotError().
constants
constants = {}
The constants stay constant unless fitted.
Definition at line 112 of file main.py.
Referenced by AnalyzeErrors(), ArrayToConstants(), BulkError(), BulkEvolver(), Evolver(), loadConstants(), loadPredictors(), parameters(), setSolveList(), and Simulate().
constraints
constraints = constraints
Definition at line 368 of file main.py.
dataLength
dataLength
The loaded dataFrame length.
Definition at line 533 of file main.py.
Referenced by AnalyzeErrors(), BulkError(), and resampleData().
DF
DF = df
The loaded pandas dataFrame.
Definition at line 543 of file main.py.
Referenced by dictSlice(), and resampleData().
dt
int dt = 1
Definition at line 120 of file main.py.
Referenced by loadVariables(), and resampleData().
error
list error = []
Definition at line 119 of file main.py.
Referenced by AnalyzeErrors(), Evolver(), plotError(), SimSolve(), and Simulate().
index
index = 0
The error array contains [index, error, [constants]].
Definition at line 118 of file main.py.
Referenced by Evolver(), resetIndex(), Simulate(), stepIndex(), and storeJson().
Instance
Instance = "{}.json".format(Instance)
Definition at line 121 of file main.py.
Referenced by storeJson().
lambdaDict
dict lambdaDict = lambdaDict
Definition at line 100 of file main.py.
Referenced by Calculate().
lambdaMap
dict lambdaMap = lambdaMap
Definition at line 90 of file main.py.
Referenced by Calculate().
LoadedInstance
LoadedInstance = self.storeJson()
Definition at line 143 of file main.py.
Referenced by loadConstants().
predictors
predictors = {}
The predictors calculated by applying lambdafunctions.
Definition at line 116 of file main.py.
Referenced by Calculate(), Evolver(), loadPredictors(), parameters(), Simulate(), and writeSlice().
pSearchMap
pSearchMap = pSearchMap
Definition at line 387 of file main.py.
SDF
SDF = pd.concat([self.SDF,pd.Series(self.predictors).to_frame().T], ignore_index=True)
The loaded dataFrame length.
The Simulated model, predictor values are written to here
Definition at line 287 of file main.py.
Referenced by resetIndex().
solveList
solveList = {}
The solvelist so that not all constants have to be fitted.
Instantiation of errorlist.
Definition at line 114 of file main.py.
Referenced by ArrayToConstants(), BulkError(), BulkEvolver(), Evolver(), loadConstants(), plotError(), scipyOptimize(), and setSolveList().
variables
variables = {"dt": 1.0}
The variables change every step.
Definition at line 110 of file main.py.
Referenced by Evolver(), loadVariables(), and parameters().
Verbose
Verbose = verbose
The verbose boolean.
Definition at line 88 of file main.py.
Referenced by AnalyzeErrors(), ArrayToConstants(), BulkError(), BulkEvolver(), Calculate(), Evolver(), Fiddler(), loadConstants(), loadPredictors(), loadVariables(), resampleData(), and scipyOptimize().
The documentation for this class was generated from the following file:
TracknTrace/TracknTrace/fimufit/mufit/main.py