Smart Meter Interpreter Documentation: TracknTrace.preprocessor.preProcessor Namespace Reference
TracknTrace.preprocessor.preProcessor Namespace Reference
Defines the smart meter (pre)processor.
Classes
class Eventor
Functions
AnalysisDealer (data, analysis)
Carnot (Tc, Th)
COP (Pth, Pel)
DerivedCategory (trends, newtrend, CategoryWeights, Verbose=0)
EnvironmentTemperatureCheck (df, ROCLimit=30.0/(12.0 *60 *60), ULimit=50.0, LLimit=-15.0, VERBOSE=0)
EventCategorizerFcn (categories, data)
Summarizes all detected events to a limited group of categories, does the same as internal class function EventCategorizer but requires data.
fracH (dt)
KNMI_Resampler (FileName, T_Columns, ScaleArray, RevertArray=None, Interval="5min", header=28, Export=False, plot=False)
KNMI file reader with different output modi.
Lambda2Tex (lmd, VERBOSE=0)
latex_to_img (tex)
linint (x1, x2, y1, y2)
logFigure (title, data, Instance, fig=None, sort=None, kind=None, verbosityLimit=None)
LogReport (msg, verbosityLimit=None)
main ()
PandasDHWWrapper (x, Inhabitants=1)
PdTtoV (x, T1, T2, Pdhw)
ProcessData ()
Example main to run if file is not being imported.
RepairCumulatives (df, VERBOSE=0)
SimilarityCheck (df, data, corrector, ULimit=50.0, LLimit=-15.0, ROCLimit=30.0/(12.0 *60 *60), VERBOSE=0)
Stochastic_Usage (H, Size=1.0)
TimeDivision (df, Columns, scaleArray=None, reverse=False)
VisualizeEvent (df, event, Instance, Extra=None, columns=None, Size=None, Type="default", Save=True)
Summarizes all detected events to a limited group of categories.
Variables
action
Ignore FutureWarning errors, floods log.
All
alpha
ambiguous
args = parser.parse_args()
Instantiate the parser.
axis
backend
plotting backend for pandas
list BaseWeights
Bestparams = fmf.constants
bestSimulation = pd.DataFrame(fmf.Simulate(steps=fmf.dataLength, err="Tavg")[-fmf.dataLength:],columns=["index","err","Tavg","Tavg_pr","U","Ag","Ga","C"])
category
list CategoryWeights = [["Combined_Categories", "User_Electric", "User_Thermal", "Building_thermal", "Installation_Electric", "Installation_Thermal", "Weather_thermal"]]
cEventCfg = config["eventdetection"]["OtherEvents"].split(",")
chained_assignment
turn of error reporting for chained assignments
color
columns
COPDC = data[["COP"]].resample("1h").mean().interpolate().sort_values("COP",ascending=False).reset_index(drop=True)
data = data.resample(config["preprocessing"]["ResampleTime"]).mean().interpolate()
~~~~~~~~~~~~~~~~~~Milestone!
dataAfternoon = TimeDivision(dataHourly,timeDivisionArray)
dataDaily = TimeDivision(data,timeDivisionArray)
dataEvening = TimeDivision(dataHourly,timeDivisionArray)
dataHourly = TimeDivision(data,timeDivisionArray)
dataMonthly = TimeDivision(data,timeDivisionArray)
dataMorning = TimeDivision(dataHourly,timeDivisionArray)
dataNight = TimeDivision(dataHourly,timeDivisionArray)
dataWeekly = TimeDivision(data,timeDivisionArray)
tuple dda = degreeDays_delta_annemarie.sum()
ddi = degreeDays_indoor.sum()
ddo = degreeDays_outdoor.sum()
default
tuple degreeDays_delta_annemarie = (data["Tavg"] - data["Tamb"]).resample("1d").mean().interpolate()
degreeDays_indoor = data["Tavg"].resample("1d").mean().interpolate().apply(lambda x: 18 - x if x > 18 else 0)
degreeDays_outdoor = data["Tamb"].resample("1d").mean().interpolate().apply(lambda x: 18 - x if x > 18 else 0)
df = pd.DataFrame(fmf.error,columns=["index","error","c0","c1"])
DHSummerSlice = data[ThermalColumns].loc["{}-05-01".format(year) : "{}-07-31".format(year)]
list dhw = [[index,dhw1], [index,dhw2], [index,dhw3], [index, dhw4], [index, dhw5], [index, dhw6], [index, dhw7], [index, dhw8]]
Domestic hot water lookup table.
list dhw1 = []
list dhw2 = []
list dhw3 = []
list dhw4 = []
list dhw5 = []
list dhw6 = []
list dhw7 = []
list dhw8 = []
DHW_Baseline = piv.mean(axis=1)
DHWColumns = config["preprocessing"]["DHWColumns"].split(",")
dt
dwstateColumns = config["preprocessing"]["DoorWindowStates"].split(",")
E_Baseline = Epiv.mean(axis=1)
Epiv = pd.pivot_table(data, index=['hour'], columns=['day'], values=['Premainder'])
errors
EventConfig = config["eventdetection"][i].split(",")
EventData = EventStudy.data[EventStudy.eventcolumns]
list Events = []
EventStudy = Eventor(data.loc[:, data.columns != 'DateTime'], VERBOSE=5)
str figname = '{}_data_processed'.format(config["preprocessing"]["Filename"].split(".")[0])
Finalcategories = pd.DataFrame(CategoryWeights[1:],columns=CategoryWeights[0], index=[i[0] for i in CategoryWeights[1:]]).drop("Combined_Categories",axis=1)
fmf = MultiFitter(Instance,lambdaMap=lambdaMap,lambdaDict=lambdaDict,verbose=2)
Function_List = getmembers(analysis, isfunction)
~~~~~~~~~~~~~~~~~ USER ANALYSIS FUNCTION MAGIC ~~~~~~~~~~~~~~~~~####
gas = int(config["schil"]["gas"])
GenericConfig = config["eventdetection"]["GenericEvents"].split(",")
str Headers = "# Table Of Content\n " + "__"*100
Headers of document.
help
HPEColumns = config["preprocessing"]["HeatPumpElectric"].split(",")
HPTColumns = config["preprocessing"]["HeatPumpThermal"].split(",")
i
list index = []
Indoor_temperatures = config["preprocessing"]["IndoorTemperatures"].split(",")
Inhabitants
initPredictors
inplace
Instance
j
kind
KNMI = KNMI_Resampler(path+"/uurgeg_290_2011-2020.txt",T_Columns,ScaleArray,header=28, Interval = "30min")
dict lambdaDict
dict lambdaMap
legend
str Log = ""
Variable contains the generated Log, equal to code output in commandline.
longWindow
lw
str MODULE = "EtoP"
~~~~~~~~~~~~~~~~~~Milestone!
mufit_html = f.read()
nonexistent
NormalizedEvents = EventStudy.EventIndicer(threshold=float(config["eventdetection"]["NormalizedEvents"]))
NPColumns = config["preprocessing"]["NegativePower"].split(",")
OS = os.environ.get('OS','')
Variable containing type of OS the code is running on.
PandasDHWWrapper
parser = argparse.ArgumentParser()
Argument parser, filled with Commandline arguments.
path = os.path.abspath(analysis.__file__)
PDC = data["Premainder"].resample("1h").mean().interpolate().sort_values("Premainder",ascending=False).reset_index(drop=True)
Pdhw
PdTtoV
piv = pd.pivot_table(data, index=['hour'], columns=['day'], values=['Vdhwcal'])
piv2 = piv.loc[:, (piv != 0).any(axis=0)]
PPColumns = config["preprocessing"]["PositivePower"].split(",")
PredictedThermal = pd.DataFrame(tp.Simulate(steps=tp.dataLength, err="HeatInput")[-tp.dataLength:],columns=["index","err","HeatInput","HeatInput_pr","U","Ag","Ga","C"])
PVArea = float(config["schil"]["pvoppervlak"])
PVColumn = config["preprocessing"]["PVPanels"].split(",")
PVDC = data[["PVEfficiency"]].resample("1h").mean().interpolate().sort_values("PVEfficiency",ascending=False).reset_index(drop=True)
regressor = LinearRegression()
list RevertArray = []
list ScaleArray = [100*100.,1.0]
sd
shortWindow
Size
SummerDetection = pd.pivot_table(data, index=["hour"], columns=["day"], values= ThermalColumns)
T1
T2
list T_Columns = [" Q"," RH"]
TDC = data[Ts].resample("1h").mean().interpolate().sort_values("dT",ascending=False).reset_index(drop=True)
test = py2tex(tex,print_formula=False, print_latex=False, output="tex").replace("$","")
tex = Lambda2Tex(lambdaDict[i])
ThermalColumns = config["preprocessing"]["ThermalColumns"].split(",")
dict ThermallambdaDict
dict ThermallambdaMap
title
tp = MultiFitter(Instance,lambdaMap=ThermallambdaMap,lambdaDict=ThermallambdaDict,verbose=2)
True
type
int Verbosity = 1
For which level of knowledge to generate a report.ssss.
verbosityLimit
tuple white = (255, 255, 255, 255)
Defining the color white for latex.
X = data[["dT"]].interpolate().bfill().ffill()
y = data[["HeatInput"]]
y_pred = regressor.predict(X)
list year = data.index[0].year
Detailed Description
Defines the smart meter (pre)processor.
Function Documentation
AnalysisDealer()
AnalysisDealer (data, analysis)
Apply all user defined functions from analysis.py to data
@param data  Standardized input (pandas)dataframe.
@param analysis  a list of [[name:function],] of user defined functions
@return data the transformed dataframe
Definition at line 709 of file preProcessor.py.
References LogReport().
Carnot()
Carnot (Tc, Th)
Calculate Carnot efficiency.
@param Tc  cold temperature in celsius.
@param Th  hot temperature in celsius.
@return Carnot efficiency
Definition at line 534 of file preProcessor.py.
COP()
COP (Pth, Pel)
Calculate Coefficient of Performance.
@param Pth  Thermal power units do not matter as long as they are both the same.
@param Pel  Electrical power, units do not matter as long as they are the same.
@return Coefficient of Performance
Definition at line 545 of file preProcessor.py.
DerivedCategory()
DerivedCategory (trends, newtrend, CategoryWeights, Verbose = 0)
Derive categories from initial guesses.
@param trends  The base trend from which to derive
@param newtrend  The derived trends which categories still need to be determined
@param CategoryWeights  The original category weights used for base trends, which will derive to new trends
@param Verbose  Verbosity switch for debugging
@return the same dataframe as trends but with newtrends added and with derived categories
Definition at line 670 of file preProcessor.py.
Referenced by ProcessData().
EnvironmentTemperatureCheck()
EnvironmentTemperatureCheck (df, ROCLimit = 30.0/(12.0*60*60), ULimit = 50.0, LLimit = -15.0, VERBOSE = 0)
Definition at line 359 of file preProcessor.py.
References linint().
EventCategorizerFcn()
EventCategorizerFcn (categories, data)
Summarizes all detected events to a limited group of categories, does the same as internal class function EventCategorizer but requires data.
Parameters
categories a list of name:category to translate any column to a new category
data a list of input data to categorize.
Returns
A new dataframe with events linked to categories
Definition at line 242 of file preProcessor.py.
fracH()
fracH (dt)
Calculate the fraction of an hour, for interpolation.
@param dt datetime time object
@return decimal number between 0 and 24
Definition at line 455 of file preProcessor.py.
Referenced by PandasDHWWrapper().
KNMI_Resampler()
KNMI_Resampler (FileName, T_Columns, ScaleArray, RevertArray = None, Interval = "5min", header = 28, Export = False, plot = False)
KNMI file reader with different output modi.
Parameters
FileName the filename with KNMI data to open, can include the path
T_Columns Time independent columns; the code needs to be aware of these in order to correctly interpolate. Array of strings.1
ScaleArray Scales T_Columns, amount of items should match T_Columns
RevertArray Revert T_Columns through the scalars given here, amount of items should match T_Columns
Interval Time interval to interpolate or extrapolate towards. Can be a string like 5s, 5min, 1h, 1d, etc.
header Number of lines to skip for the header line. Open the input file to find this.
Export If the resulting data needs to be exported to .CSV for future use or not. True or False
plot If set to True, a plot will be opened on completion.
Returns
A Pandas dataFrame transformed as configured
Definition at line 581 of file preProcessor.py.
References TimeDivision().
Lambda2Tex()
Lambda2Tex (lmd, VERBOSE = 0)
Convert Lambda system of equations to latex
@param lmd  lambda function to convert
@param VERBOSE  retardcounter higher = less retarded
@return the converted equation in tex format
Definition at line 642 of file preProcessor.py.
latex_to_img()
latex_to_img (tex)
Convert Latex expression to .png image
@param tex  the latex expression to convert to an image
@return an html compatible image? (check this!)
Definition at line 621 of file preProcessor.py.
linint()
linint (x1, x2, y1, y2)
Linear interpolation.
@param x1  value  (x2-x1)
@param x2  value  (x2-x1)
@param y1  value  delta = y2-y1
@param y2  value  delta = y2-y1
@return x2-x1 frames interpolated between y2 and y1
Definition at line 317 of file preProcessor.py.
Referenced by EnvironmentTemperatureCheck(), and RepairCumulatives().
logFigure()
logFigure (title, data, Instance, fig = None, sort = None, kind = None, verbosityLimit = None)
Add figure to the created log. And make sure it is rendered properly in HTML
@param title  the name of the figure under which it will be saved
@param data  the data to plot in the figure
@param fig  the figure object to plot, to allow customization but still end up in log/report.
@param sort  If the data to be plotted needs to be sorted or not, generates time-duration curves.
@param kind  type of matplotlib plot to generate (line, bar, etc.)
@param return  Adds figure to Log, either HTML or a link to the output figure.
Definition at line 500 of file preProcessor.py.
References LogReport().
Referenced by ProcessData().
LogReport()
LogReport (msg, verbosityLimit = None)
Function to unify logging, messaging, errors and report generation.
@param msg  Message to append to log or report
@param verbosityLimit The verbosity number connected to this message.
@return sets Log, Verbosity and Headers for every message
Definition at line 478 of file preProcessor.py.
Referenced by AnalysisDealer(), logFigure(), and ProcessData().
main()
main ()
Definition at line 1505 of file preProcessor.py.
References ProcessData().
PandasDHWWrapper()
PandasDHWWrapper (x, Inhabitants = 1)
Wrap for Domestic Hot Water empirical equation for Pandas Apply.
@param x  a pandas dataframe to which DHW will be appended
@param Inhabitants  amount of inhabitants for which to generate a DHW profile
@return DHW profile for
Definition at line 467 of file preProcessor.py.
References fracH(), and Stochastic_Usage().
PdTtoV()
PdTtoV (x, T1, T2, Pdhw)
Calculate DHW flow rate based on temperature difference and power.
@param x  series with power of domestic hot water
@param T1  value  (x2-x1)
@param T2  value  delta = y2-y1
@param y2  value  delta = y2-y1
@return x2-x1 frames interpolated between y2 and y1
Definition at line 441 of file preProcessor.py.
ProcessData()
ProcessData ()
Example main to run if file is not being imported.
Definition at line 756 of file preProcessor.py.
References DerivedCategory(), logFigure(), LogReport(), and RepairCumulatives().
Referenced by main().
RepairCumulatives()
RepairCumulatives (df, VERBOSE = 0)
Repair cumulative trends from smart meter data.
@param df  input cumulative trends dataframe to repair
@param VERBOSE  verbosity switch to generate reports for different levels of knowledge
@return dataframe with actually cumulative trends.
Definition at line 398 of file preProcessor.py.
References linint().
Referenced by ProcessData().
SimilarityCheck()
SimilarityCheck (df, data, corrector, ULimit = 50.0, LLimit = -15.0, ROCLimit = 30.0/(12.0*60*60), VERBOSE = 0)
General sanity and similarity check
@param df  base dataframe containing all series to work with
@param data  name of column in dataframe which needs to be corrected
@param corrector  name of column in dataframe which can be used to correct data
@param ULimit  the upper limit, exceeding this value means that values from corrector will be taken
@param LLimit  the lower limit, going below this value means that values from corrector will be taken
@param ROCLimit  if this Rate Of Change is exceeded, values from corrector are taken
@param VERBOSE  if this value is bigger the 0, corrected values will be reported in the log with more details
@return The original dataframe but with the data column fixed according to above  rules.
Definition at line 332 of file preProcessor.py.
Stochastic_Usage()
Stochastic_Usage (H, Size = 1.0)
Empirical equation for Domestic Hot Water usage.
@param H  Hour of the day for which to get the L/h value
@param Size  size of household, number of inhabitants
@return  A new dataframe with events linked to categories
Definition at line 299 of file preProcessor.py.
Referenced by PandasDHWWrapper().
TimeDivision()
TimeDivision (df, Columns, scaleArray = None, reverse = False)
Find delta in dataset and divide Columns by time.
@param df  input dataset containing columns to divide by time
@param Columns  Columns to divide by time. Delta will be detected automatically
@param scaleArray  Scaling to apply when dividing by time
@param reverse  Reverse the operation or not.
@return df  return the transformed dataframe. Calling same function with identical arguments but reverse = True returns to the original.
Definition at line 559 of file preProcessor.py.
Referenced by KNMI_Resampler().
VisualizeEvent()
VisualizeEvent (df, event, Instance, Extra = None, columns = None, Size = None, Type = "default", Save = True)
Summarizes all detected events to a limited group of categories.
Parameters
event finish this!!
Returns
A new dataframe with events linked to categories
Definition at line 258 of file preProcessor.py.
Variable Documentation
action
action
Ignore FutureWarning errors, floods log.
Definition at line 77 of file preProcessor.py.
All
All
Definition at line 1207 of file preProcessor.py.
alpha
alpha
Definition at line 1235 of file preProcessor.py.
ambiguous
ambiguous
Definition at line 1452 of file preProcessor.py.
args
args = parser.parse_args()
Instantiate the parser.
Definition at line 98 of file preProcessor.py.
axis
axis
Definition at line 976 of file preProcessor.py.
backend
backend
plotting backend for pandas
Definition at line 86 of file preProcessor.py.
BaseWeights
list BaseWeights
Initial value:
=  [["Combined_Categories", "User_Electric", "User_Thermal", "Building_thermal", "Installation_Electric", "Installation_Thermal", "Weather_thermal"],
                ["Tlive", 0, 0.9, 0.05, 0, 0.05, 0],
                ["Ttraffic", 0, 0.5, 0, 0, 0.2, 0.3],
                ["Tambient", 0, 0.5, 0, 0, 0.2, 0.3],
                ["Emachine", 0.1, 0.1, 0.2, 0.5, 0.1, 0]]
Definition at line 663 of file preProcessor.py.
Bestparams
Bestparams = fmf.constants
Definition at line 1154 of file preProcessor.py.
bestSimulation
bestSimulation = pd.DataFrame(fmf.Simulate(steps=fmf.dataLength, err="Tavg")[-fmf.dataLength:],columns=["index","err","Tavg","Tavg_pr","U","Ag","Ga","C"])
Definition at line 1159 of file preProcessor.py.
category
category
Definition at line 77 of file preProcessor.py.
CategoryWeights
list CategoryWeights = [["Combined_Categories", "User_Electric", "User_Thermal", "Building_thermal", "Installation_Electric", "Installation_Thermal", "Weather_thermal"]]
Definition at line 662 of file preProcessor.py.
cEventCfg
cEventCfg = config["eventdetection"]["OtherEvents"].split(",")
Definition at line 1408 of file preProcessor.py.
chained_assignment
chained_assignment
turn of error reporting for chained assignments
Definition at line 88 of file preProcessor.py.
color
color
Definition at line 1075 of file preProcessor.py.
columns
columns
Definition at line 1007 of file preProcessor.py.
COPDC
COPDC = data[["COP"]].resample("1h").mean().interpolate().sort_values("COP",ascending=False).reset_index(drop=True)
Definition at line 1232 of file preProcessor.py.
data
data = data.resample(config["preprocessing"]["ResampleTime"]).mean().interpolate()
~~~~~~~~~~~~~~~~~~Milestone!
Definition at line 901 of file preProcessor.py.
dataAfternoon
dataAfternoon = TimeDivision(dataHourly,timeDivisionArray)
Definition at line 1486 of file preProcessor.py.
dataDaily
dataDaily = TimeDivision(data,timeDivisionArray)
Definition at line 1463 of file preProcessor.py.
dataEvening
dataEvening = TimeDivision(dataHourly,timeDivisionArray)
Definition at line 1491 of file preProcessor.py.
dataHourly
dataHourly = TimeDivision(data,timeDivisionArray)
Definition at line 1457 of file preProcessor.py.
dataMonthly
dataMonthly = TimeDivision(data,timeDivisionArray)
Definition at line 1475 of file preProcessor.py.
dataMorning
dataMorning = TimeDivision(dataHourly,timeDivisionArray)
Definition at line 1481 of file preProcessor.py.
dataNight
dataNight = TimeDivision(dataHourly,timeDivisionArray)
Definition at line 1496 of file preProcessor.py.
dataWeekly
dataWeekly = TimeDivision(data,timeDivisionArray)
Definition at line 1469 of file preProcessor.py.
dda
tuple dda = degreeDays_delta_annemarie.sum()
Definition at line 995 of file preProcessor.py.
ddi
ddi = degreeDays_indoor.sum()
Definition at line 991 of file preProcessor.py.
ddo
ddo = degreeDays_outdoor.sum()
Definition at line 993 of file preProcessor.py.
default
default
Definition at line 95 of file preProcessor.py.
degreeDays_delta_annemarie
tuple degreeDays_delta_annemarie = (data["Tavg"] - data["Tamb"]).resample("1d").mean().interpolate()
Definition at line 994 of file preProcessor.py.
degreeDays_indoor
degreeDays_indoor = data["Tavg"].resample("1d").mean().interpolate().apply(lambda x: 18 - x if x > 18 else 0)
Definition at line 990 of file preProcessor.py.
degreeDays_outdoor
degreeDays_outdoor = data["Tamb"].resample("1d").mean().interpolate().apply(lambda x: 18 - x if x > 18 else 0)
Definition at line 992 of file preProcessor.py.
df
df = pd.DataFrame(fmf.error,columns=["index","error","c0","c1"])
Definition at line 1139 of file preProcessor.py.
DHSummerSlice
DHSummerSlice = data[ThermalColumns].loc["{}-05-01".format(year) : "{}-07-31".format(year)]
Definition at line 1297 of file preProcessor.py.
dhw
list dhw = [[index,dhw1], [index,dhw2], [index,dhw3], [index, dhw4], [index, dhw5], [index, dhw6], [index, dhw7], [index, dhw8]]
Domestic hot water lookup table.
Definition at line 753 of file preProcessor.py.
dhw1
list dhw1 = []
Definition at line 732 of file preProcessor.py.
dhw2
list dhw2 = []
Definition at line 733 of file preProcessor.py.
dhw3
list dhw3 = []
Definition at line 734 of file preProcessor.py.
dhw4
list dhw4 = []
Definition at line 735 of file preProcessor.py.
dhw5
list dhw5 = []
Definition at line 736 of file preProcessor.py.
dhw6
list dhw6 = []
Definition at line 737 of file preProcessor.py.
dhw7
list dhw7 = []
Definition at line 738 of file preProcessor.py.
dhw8
list dhw8 = []
Definition at line 739 of file preProcessor.py.
DHW_Baseline
DHW_Baseline = piv.mean(axis=1)
Definition at line 1322 of file preProcessor.py.
DHWColumns
DHWColumns = config["preprocessing"]["DHWColumns"].split(",")
Definition at line 1292 of file preProcessor.py.
dt
dt
Definition at line 1140 of file preProcessor.py.
dwstateColumns
dwstateColumns = config["preprocessing"]["DoorWindowStates"].split(",")
Definition at line 1033 of file preProcessor.py.
E_Baseline
E_Baseline = Epiv.mean(axis=1)
Definition at line 1266 of file preProcessor.py.
Epiv
Epiv = pd.pivot_table(data, index=['hour'], columns=['day'], values=['Premainder'])
Definition at line 1262 of file preProcessor.py.
errors
errors
Definition at line 1209 of file preProcessor.py.
EventConfig
EventConfig = config["eventdetection"][i].split(",")
Definition at line 1411 of file preProcessor.py.
EventData
EventData = EventStudy.data[EventStudy.eventcolumns]
Definition at line 1424 of file preProcessor.py.
Events
list Events = []
Definition at line 1409 of file preProcessor.py.
EventStudy
EventStudy = Eventor(data.loc[:, data.columns != 'DateTime'], VERBOSE=5)
Definition at line 1000 of file preProcessor.py.
figname
str figname = '{}_data_processed'.format(config["preprocessing"]["Filename"].split(".")[0])
Definition at line 1423 of file preProcessor.py.
Finalcategories
Finalcategories = pd.DataFrame(CategoryWeights[1:],columns=CategoryWeights[0], index=[i[0] for i in CategoryWeights[1:]]).drop("Combined_Categories",axis=1)
Definition at line 1440 of file preProcessor.py.
fmf
fmf = MultiFitter(Instance,lambdaMap=lambdaMap,lambdaDict=lambdaDict,verbose=2)
Definition at line 1135 of file preProcessor.py.
Function_List
Function_List = getmembers(analysis, isfunction)
~~~~~~~~~~~~~~~~~ USER ANALYSIS FUNCTION MAGIC ~~~~~~~~~~~~~~~~~####
Definition at line 966 of file preProcessor.py.
gas
gas = int(config["schil"]["gas"])
Definition at line 1014 of file preProcessor.py.
GenericConfig
GenericConfig = config["eventdetection"]["GenericEvents"].split(",")
Definition at line 1001 of file preProcessor.py.
Headers
str Headers = "# Table Of Content\n " + "__"*100
Headers of document.
Created Table of Content.
Definition at line 728 of file preProcessor.py.
help
help
Definition at line 93 of file preProcessor.py.
HPEColumns
HPEColumns = config["preprocessing"]["HeatPumpElectric"].split(",")
Definition at line 1220 of file preProcessor.py.
HPTColumns
HPTColumns = config["preprocessing"]["HeatPumpThermal"].split(",")
Definition at line 1221 of file preProcessor.py.
i
i
Definition at line 1402 of file preProcessor.py.
index
index = []
Definition at line 740 of file preProcessor.py.
Indoor_temperatures
Indoor_temperatures = config["preprocessing"]["IndoorTemperatures"].split(",")
Definition at line 975 of file preProcessor.py.
Inhabitants
Inhabitants
Definition at line 1300 of file preProcessor.py.
initPredictors
initPredictors
Definition at line 1136 of file preProcessor.py.
inplace
inplace
Definition at line 1182 of file preProcessor.py.
Instance
Instance
Definition at line 1160 of file preProcessor.py.
j
j
Definition at line 1419 of file preProcessor.py.
kind
kind
Definition at line 1443 of file preProcessor.py.
KNMI
KNMI = KNMI_Resampler(path+"/uurgeg_290_2011-2020.txt",T_Columns,ScaleArray,header=28, Interval = "30min")
Definition at line 925 of file preProcessor.py.
lambdaDict
dict lambdaDict
Initial value:
=  {"Qtr": lambda Tamb, Tavg, U: (Tamb-Tavg)*0.001/ U,
                      "Qcv": lambda HeatInput: HeatInput,
                      "Qsol": lambda P_sun, Ag, Ga: P_sun*0.001*Ag*Ga,
                      "dTobj": lambda Qsol, Qcv, Qtr, dt, C: (Qtr+Qcv+Qsol)*dt/C,
                      "Tavg": lambda Tavg, dTobj: Tavg + dTobj}
Definition at line 1097 of file preProcessor.py.
lambdaMap
dict lambdaMap
Initial value:
=  {"Qtr": ["Tamb","Tavg","$U"],
                     "Qcv":["HeatInput"],
                     "Qsol":["P-sun","*Ag","$Ga"], # where Ag = glass area and Ga = solar irradiance factor, for solver!
                     "dTobj":["Qsol","Qcv","Qtr","dt","$C"],
                     "Tavg":["Tavg","dTobj"]}
Definition at line 1091 of file preProcessor.py.
legend
legend
Definition at line 1060 of file preProcessor.py.
Log
str Log = ""
Variable contains the generated Log, equal to code output in commandline.
Definition at line 726 of file preProcessor.py.
longWindow
longWindow
Definition at line 1007 of file preProcessor.py.
lw
lw
Definition at line 1060 of file preProcessor.py.
MODULE
str MODULE = "EtoP"
~~~~~~~~~~~~~~~~~~Milestone!
~~~~~~~~~~~~~~~~~ USER ANALYSIS FUNCTION MAGIC ~~~~~~~~~~~~~~~~~####
Definition at line 904 of file preProcessor.py.
mufit_html
mufit_html = f.read()
Definition at line 1210 of file preProcessor.py.
nonexistent
nonexistent
Definition at line 1452 of file preProcessor.py.
NormalizedEvents
NormalizedEvents = EventStudy.EventIndicer(threshold=float(config["eventdetection"]["NormalizedEvents"]))
Definition at line 1396 of file preProcessor.py.
NPColumns
NPColumns = config["preprocessing"]["NegativePower"].split(",")
Definition at line 1252 of file preProcessor.py.
OS
OS = os.environ.get('OS','')
Variable containing type of OS the code is running on.
Definition at line 82 of file preProcessor.py.
PandasDHWWrapper
PandasDHWWrapper
Definition at line 1300 of file preProcessor.py.
parser
parser = argparse.ArgumentParser()
Argument parser, filled with Commandline arguments.
Definition at line 91 of file preProcessor.py.
path
str path = os.path.abspath(analysis.__file__)
Definition at line 921 of file preProcessor.py.
PDC
PDC = data["Premainder"].resample("1h").mean().interpolate().sort_values("Premainder",ascending=False).reset_index(drop=True)
Definition at line 1350 of file preProcessor.py.
Pdhw
Pdhw
Definition at line 1298 of file preProcessor.py.
PdTtoV
PdTtoV
Definition at line 1298 of file preProcessor.py.
piv
piv = pd.pivot_table(data, index=['hour'], columns=['day'], values=['Vdhwcal'])
Definition at line 1317 of file preProcessor.py.
piv2
piv2 = piv.loc[:, (piv != 0).any(axis=0)]
Definition at line 1318 of file preProcessor.py.
PPColumns
PPColumns = config["preprocessing"]["PositivePower"].split(",")
Definition at line 1251 of file preProcessor.py.
PredictedThermal
PredictedThermal = pd.DataFrame(tp.Simulate(steps=tp.dataLength, err="HeatInput")[-tp.dataLength:],columns=["index","err","HeatInput","HeatInput_pr","U","Ag","Ga","C"])
Definition at line 1172 of file preProcessor.py.
PVArea
PVArea = float(config["schil"]["pvoppervlak"])
Definition at line 1045 of file preProcessor.py.
PVColumn
PVColumn = config["preprocessing"]["PVPanels"].split(",")
Definition at line 1044 of file preProcessor.py.
PVDC
PVDC = data[["PVEfficiency"]].resample("1h").mean().interpolate().sort_values("PVEfficiency",ascending=False).reset_index(drop=True)
Definition at line 1057 of file preProcessor.py.
regressor
regressor = LinearRegression()
Definition at line 1071 of file preProcessor.py.
RevertArray
list RevertArray = []
Definition at line 920 of file preProcessor.py.
ScaleArray
list ScaleArray = [100*100.,1.0]
Definition at line 919 of file preProcessor.py.
sd
sd
Definition at line 1007 of file preProcessor.py.
shortWindow
shortWindow
Definition at line 1007 of file preProcessor.py.
Size
Size
Definition at line 1402 of file preProcessor.py.
SummerDetection
SummerDetection = pd.pivot_table(data, index=["hour"], columns=["day"], values= ThermalColumns)
Definition at line 1310 of file preProcessor.py.
T1
T1
Definition at line 1298 of file preProcessor.py.
T2
T2
Definition at line 1298 of file preProcessor.py.
T_Columns
list T_Columns = [" Q"," RH"]
Definition at line 918 of file preProcessor.py.
TDC
TDC = data[Ts].resample("1h").mean().interpolate().sort_values("dT",ascending=False).reset_index(drop=True)
Definition at line 1367 of file preProcessor.py.
test
test = py2tex(tex,print_formula=False, print_latex=False, output="tex").replace("$","")
Definition at line 1129 of file preProcessor.py.
tex
tex = Lambda2Tex(lambdaDict[i])
Definition at line 1124 of file preProcessor.py.
ThermalColumns
ThermalColumns = config["preprocessing"]["ThermalColumns"].split(",")
Definition at line 1013 of file preProcessor.py.
ThermallambdaDict
dict ThermallambdaDict
Initial value:
=  {"Qtr": lambda Tamb, Tavg, U: (Tamb-Tavg)*0.001/ U,
                             "HeatInput": lambda dT, C, dt, Qtr, Qsol: ((dT*C/dt) - Qtr - Qsol)*0.001,
                             "Qsol": lambda P_sun, Ag, Ga: P_sun*0.001*Ag*Ga,
                             "dTobj": lambda dTobj: dTobj, # (Qtr+HeatInput+Qsol)*dt/C = dT,
                             "Tavg": lambda Tavg, dTobj: Tavg + dTobj}
Definition at line 1110 of file preProcessor.py.
ThermallambdaMap
dict ThermallambdaMap
Initial value:
=  {"Qtr": ["Tamb","Tavg","$U"],
                            "HeatInput":["dT", "$C", "dt", "Qtr", "Qsol"],
                            "Qsol":["P-sun","*Ag","$Ga"], # where Ag = glass area and Ga = solar irradiance factor, for solver!
                            "dTobj":["dTobj"],
                            "Tavg":["Tavg","dTobj"]}
Definition at line 1104 of file preProcessor.py.
title
title
Definition at line 1264 of file preProcessor.py.
tp
tp = MultiFitter(Instance,lambdaMap=ThermallambdaMap,lambdaDict=ThermallambdaDict,verbose=2)
Definition at line 1168 of file preProcessor.py.
True
True
Definition at line 1060 of file preProcessor.py.
type
type
Definition at line 92 of file preProcessor.py.
Verbosity
int Verbosity = 1
For which level of knowledge to generate a report.ssss.
Definition at line 730 of file preProcessor.py.
verbosityLimit
verbosityLimit
Definition at line 1160 of file preProcessor.py.
white
tuple white = (255, 255, 255, 255)
Defining the color white for latex.
Definition at line 619 of file preProcessor.py.
X
X = data[["dT"]].interpolate().bfill().ffill()
Definition at line 1069 of file preProcessor.py.
y
y = data[["HeatInput"]]
Definition at line 1070 of file preProcessor.py.
y_pred
y_pred = regressor.predict(X)
Definition at line 1073 of file preProcessor.py.
year
list year = data.index[0].year
Definition at line 1294 of file preProcessor.py.